# Generated by Django 4.2.19 on 2025-03-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(4, '4级'), (1, '1级'), (2, '2级'), (3, '3级')], default=1, verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('k3', models.CharField(max_length=64, verbose_name='K3')),
                ('sales_volume', models.IntegerField(verbose_name='实发数量(Kg)')),
                ('net_unit_price', models.DecimalField(decimal_places=14, default=0, max_digits=27, verbose_name='不含税单价(元/Kg)')),
                ('client_company', models.CharField(max_length=64, verbose_name='实际购货公司')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='销售团队名称')),
                ('business_area', models.CharField(blank=True, max_length=64, null=True, verbose_name='业务区域')),
                ('business_segment', models.CharField(blank=True, max_length=64, null=True, verbose_name='业务板块描述')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateField(verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '一般')], default=2, verbose_name='级别')),
                ('tittle', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='任务详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='销售人员姓名')),
                ('status', models.SmallIntegerField(choices=[(2, '经理'), (1, '组员')], default=1, verbose_name='级别')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.salesteam', verbose_name='团队')),
            ],
        ),
        migrations.CreateModel(
            name='SalesIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='年份')),
                ('target_sales_volume_1', models.IntegerField(default=0, verbose_name='1月销量指标(Kg)')),
                ('target_sales_volume_2', models.IntegerField(default=0, verbose_name='2月销量指标(Kg)')),
                ('target_sales_volume_3', models.IntegerField(default=0, verbose_name='3月销量指标(Kg)')),
                ('target_sales_volume_4', models.IntegerField(default=0, verbose_name='4月销量指标(Kg)')),
                ('target_sales_volume_5', models.IntegerField(default=0, verbose_name='5月销量指标(Kg)')),
                ('target_sales_volume_6', models.IntegerField(default=0, verbose_name='6月销量指标(Kg)')),
                ('target_sales_volume_7', models.IntegerField(default=0, verbose_name='7月销量指标(Kg)')),
                ('target_sales_volume_8', models.IntegerField(default=0, verbose_name='8月销量指标(Kg)')),
                ('target_sales_volume_9', models.IntegerField(default=0, verbose_name='9月销量指标(Kg)')),
                ('target_sales_volume_10', models.IntegerField(default=0, verbose_name='10月销量指标(Kg)')),
                ('target_sales_volume_11', models.IntegerField(default=0, verbose_name='11月销量指标(Kg)')),
                ('target_sales_volume_12', models.IntegerField(default=0, verbose_name='12月销量指标(Kg)')),
                ('target_sales_revenue_1', models.IntegerField(default=0, verbose_name='1月销售额指标(元)')),
                ('target_sales_revenue_2', models.IntegerField(default=0, verbose_name='2月销售额指标(元)')),
                ('target_sales_revenue_3', models.IntegerField(default=0, verbose_name='3月销售额指标(元)')),
                ('target_sales_revenue_4', models.IntegerField(default=0, verbose_name='4月销售额指标(元)')),
                ('target_sales_revenue_5', models.IntegerField(default=0, verbose_name='5月销售额指标(元)')),
                ('target_sales_revenue_6', models.IntegerField(default=0, verbose_name='6月销售额指标(元)')),
                ('target_sales_revenue_7', models.IntegerField(default=0, verbose_name='7月销售额指标(元)')),
                ('target_sales_revenue_8', models.IntegerField(default=0, verbose_name='8月销售额指标(元)')),
                ('target_sales_revenue_9', models.IntegerField(default=0, verbose_name='9月销售额指标(元)')),
                ('target_sales_revenue_10', models.IntegerField(default=0, verbose_name='10月销售额指标(元)')),
                ('target_sales_revenue_11', models.IntegerField(default=0, verbose_name='11月销售额指标(元)')),
                ('target_sales_revenue_12', models.IntegerField(default=0, verbose_name='12月销售额指标(元)')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.salesperson', verbose_name='成员')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('tittle', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='管理员')),
            ],
        ),
    ]
