# Generated by Django 4.2.19 on 2025-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (1, '1级'), (3, '3级'), (4, '4级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='salesindicator',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '组员'), (2, '经理')], default=1, verbose_name='级别'),
        ),
    ]
