# Generated by Django 4.2.19 on 2025-03-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_order_status_alter_prettynum_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_or_external_sales', models.CharField(max_length=64, verbose_name='客户类型(内外销)')),
                ('supply_company', models.CharField(max_length=64, verbose_name='供货基地')),
                ('salesperson', models.CharField(max_length=64, verbose_name='业务员')),
                ('product_domain_groups', models.CharField(max_length=64, verbose_name='组别（电子电气、家电、汽配、卫浴、内销、原料销售、国内营销、国际营销、精密组件）')),
                ('initial_transaction_date', models.DateField(verbose_name='初始交易日期')),
                ('actual_client_company', models.CharField(max_length=64, verbose_name='客户全称')),
                ('k3', models.CharField(max_length=64, verbose_name='K3')),
                ('product_name', models.CharField(max_length=64, verbose_name='材料名称')),
                ('product_category', models.CharField(max_length=64, verbose_name='产品线')),
                ('core_product', models.CharField(max_length=64, verbose_name='主打产品')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (3, '3级'), (2, '2级'), (1, '1级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已占用'), (1, '未占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '经理'), (1, '组员')], default=1, verbose_name='级别'),
        ),
    ]
