# Generated by Django 4.2.19 on 2025-02-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_prettynum_userinfo_task_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='销售团队名称')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (4, '4级'), (3, '3级'), (1, '1级')], default=1, verbose_name='等级'),
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='销售人员姓名')),
                ('status', models.SmallIntegerField(choices=[(2, '经理'), (1, '组员')], default=1, verbose_name='级别')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.salesteam', verbose_name='团队')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('target', models.IntegerField(verbose_name='目标量')),
                ('target_achievement', models.IntegerField(verbose_name='完成量')),
                ('sales_revenue', models.IntegerField(verbose_name='销售额')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.salesperson', verbose_name='成员')),
            ],
        ),
    ]
