# Generated by Django 4.2.19 on 2025-03-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_salesproduct_alter_prettynum_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (1, '1级'), (4, '4级'), (3, '3级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '组员'), (2, '经理')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='core_product',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主打产品'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='product_category',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='产品线'),
        ),
    ]
