# Generated by Django 4.2.19 on 2025-02-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_salesteam_alter_prettynum_level_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.salesteam', verbose_name='团队'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='month',
            field=models.DateField(verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='sales_revenue',
            field=models.IntegerField(verbose_name='当月销售额'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target',
            field=models.IntegerField(verbose_name='当月目标量'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target_achievement',
            field=models.IntegerField(verbose_name='当月完成量'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (1, '1级'), (3, '3级'), (4, '4级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已占用'), (1, '未占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '组员'), (2, '经理')], default=1, verbose_name='级别'),
        ),
    ]
