# Generated by Django 4.2.19 on 2025-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target_sales_revenue',
            field=models.IntegerField(default=0, verbose_name='当月销售额任务指标(元)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target_sales_volume',
            field=models.IntegerField(default=0, verbose_name='当月销售量任务指标(Kg)'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (4, '4级'), (1, '1级'), (3, '3级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '组员'), (2, '经理')], default=1, verbose_name='级别'),
        ),
    ]
