# Generated by Django 4.2.19 on 2025-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_performance_team_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='team',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态'),
        ),
    ]
