# Generated by Django 4.2.19 on 2025-02-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_performance_team_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('order_number', models.CharField(max_length=64, verbose_name='单据编号')),
                ('client_company', models.CharField(max_length=64, verbose_name='购货公司')),
                ('k3', models.CharField(max_length=64, verbose_name='产品长代码')),
                ('product_name', models.CharField(max_length=64, verbose_name='产品名称')),
                ('product_specification', models.CharField(max_length=64, verbose_name='规格型号')),
                ('sales_volume', models.IntegerField(verbose_name='实发数量(Kg)')),
                ('department', models.CharField(max_length=64, verbose_name='部门')),
                ('salesperson', models.CharField(max_length=64, verbose_name='业务员')),
                ('gross_unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='销售单价(元/Kg）')),
                ('net_unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='不含税单价（元/Kg）')),
                ('actual_client_company', models.CharField(max_length=64, verbose_name='实际购货公司')),
                ('supply_company', models.CharField(max_length=64, verbose_name='供货基地')),
                ('intra_group_or_external_sales', models.CharField(max_length=64, verbose_name='内外销（内销、外销）')),
                ('product_domain_groups', models.CharField(max_length=64, verbose_name='组别（电子电气、家电、汽配、卫浴、内销、贸易）')),
                ('business_trade_categories', models.CharField(max_length=64, verbose_name='贸易类型组别')),
                ('new_and_returning_customers', models.CharField(max_length=64, verbose_name='新老客户')),
                ('product_category', models.CharField(max_length=64, verbose_name='产品线')),
                ('core_product', models.CharField(max_length=64, verbose_name='主打产品')),
                ('order_type', models.CharField(max_length=64, verbose_name='订单类别')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target',
            field=models.IntegerField(verbose_name='当月指标任务'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='target_achievement',
            field=models.IntegerField(verbose_name='当月指标达成'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '经理'), (1, '组员')], default=1, verbose_name='级别'),
        ),
    ]
