# Generated by Django 4.2.19 on 2025-02-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_salesdata_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (4, '4级'), (1, '1级'), (3, '3级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已占用'), (1, '未占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='gross_unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='销售单价(元/Kg)'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='intra_group_or_external_sales',
            field=models.CharField(max_length=64, verbose_name='内外销(内销、外销)'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='net_unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='不含税单价(元/Kg)'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='product_domain_groups',
            field=models.CharField(max_length=64, verbose_name='产品分类(电子电气、家电、汽配、卫浴、内销、贸易)'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '组员'), (2, '经理')], default=1, verbose_name='级别'),
        ),
    ]
