# Generated by Django 4.2.19 on 2025-02-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_order_status_alter_prettynum_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (4, '4级'), (3, '3级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='business_trade_categories',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='贸易类型组别'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '经理'), (1, '组员')], default=1, verbose_name='级别'),
        ),
    ]
