# Generated by Django 4.2.19 on 2025-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_prettynum_level_alter_prettynum_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (4, '4级'), (3, '3级'), (2, '2级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='core_product',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主打产品'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='product_category',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '组员'), (2, '经理')], default=1, verbose_name='级别'),
        ),
    ]
