# Generated by Django 4.2.19 on 2025-02-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_order_status_alter_prettynum_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesteam',
            name='business_area',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务区域'),
        ),
        migrations.AddField(
            model_name='salesteam',
            name='business_segment',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='业务板块描述'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (1, '1级'), (4, '4级'), (3, '3级')], default=1, verbose_name='等级'),
        ),
    ]
