# Generated by Django 4.2.19 on 2025-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_salesteam_business_area_salesteam_business_segment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '待支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (4, '4级'), (3, '3级')], default=1, verbose_name='等级'),
        ),
    ]
