# Generated by Django 4.2.19 on 2025-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_order_status_alter_prettynum_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(3, '3级'), (4, '4级'), (2, '2级'), (1, '1级')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已占用'), (1, '未占用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='gross_unit_price',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=27, verbose_name='销售单价(元/Kg)'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='k3',
            field=models.CharField(max_length=64, verbose_name='K3'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='net_unit_price',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=27, verbose_name='不含税单价(元/Kg)'),
        ),
    ]
