name: sw_bi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: sw_bi
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
