name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    # Checkout code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v4
#    - name: sw_bi
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up the build process
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Login to Docker Hub or GitHub Container Registry (GHCR)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub token

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t sw_bi:latest .

    # Push Docker image to Docker Hub (or GHCR)
    - name: Push Docker image to Docker Hub
      run: |
        docker tag sw_bi:latest ${{ secrets.DOCKER_USERNAME }}/sw_bi:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/sw_bi:latest
